// <auto-generated />
using MakeTheGradeAPI.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MakeTheGradeAPI.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210420095318_NewCreate")]
    partial class NewCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0-preview.2.21154.2");

            modelBuilder.Entity("MakeTheGradeAPI.Entities.Catalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ExamId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("exam_id");

                    b.Property<int>("Grade")
                        .HasColumnType("INTEGER")
                        .HasColumnName("grade");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("student_id");

                    b.Property<int>("TeacherId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("teacher_id");

                    b.HasKey("Id");

                    b.ToTable("Catalog");
                });

            modelBuilder.Entity("MakeTheGradeAPI.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Credits")
                        .HasColumnType("int")
                        .HasColumnName("credits");

                    b.Property<string>("Title")
                        .HasColumnType("string")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("MakeTheGradeAPI.Entities.EssayTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("EssayText")
                        .HasColumnType("string")
                        .HasColumnName("essay_text");

                    b.Property<int>("ExamId")
                        .HasColumnType("int")
                        .HasColumnName("exam_id");

                    b.Property<string>("Question")
                        .HasColumnType("string")
                        .HasColumnName("question");

                    b.HasKey("Id");

                    b.ToTable("EssayTest");
                });

            modelBuilder.Entity("MakeTheGradeAPI.Entities.Exam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("course_id");

                    b.HasKey("Id");

                    b.ToTable("Exam");
                });

            modelBuilder.Entity("MakeTheGradeAPI.Entities.MultipleChoiceTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CorrectAnswers")
                        .HasColumnType("string")
                        .HasColumnName("correctAnswers");

                    b.Property<int>("ExamId")
                        .HasColumnType("int")
                        .HasColumnName("exam_id");

                    b.Property<string>("PossibleAnswers")
                        .HasColumnType("string")
                        .HasColumnName("possibleAnswers");

                    b.Property<string>("Question")
                        .HasColumnType("string")
                        .HasColumnName("question");

                    b.HasKey("Id");

                    b.ToTable("MultipleChoiceTest");
                });

            modelBuilder.Entity("MakeTheGradeAPI.Entities.ShortAnswerTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Answer")
                        .HasColumnType("string")
                        .HasColumnName("answer");

                    b.Property<int>("ExamId")
                        .HasColumnType("int")
                        .HasColumnName("exam_id");

                    b.Property<string>("Question")
                        .HasColumnType("string")
                        .HasColumnName("question");

                    b.HasKey("Id");

                    b.ToTable("ShortAnswerTest");
                });

            modelBuilder.Entity("MakeTheGradeAPI.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("string")
                        .HasColumnName("address");

                    b.Property<string>("Email")
                        .HasColumnType("string")
                        .HasColumnName("email");

                    b.Property<string>("NumarMatricol")
                        .HasColumnType("string")
                        .HasColumnName("nr_matricol");

                    b.Property<string>("Password")
                        .HasColumnType("string")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("string")
                        .HasColumnName("phoneNumber");

                    b.Property<string>("Username")
                        .HasColumnType("string")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("MakeTheGradeAPI.Entities.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("string")
                        .HasColumnName("address");

                    b.Property<string>("Email")
                        .HasColumnType("string")
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .HasColumnType("string")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("string")
                        .HasColumnName("phoneNumber");

                    b.Property<string>("Username")
                        .HasColumnType("string")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("Teacher");
                });
#pragma warning restore 612, 618
        }
    }
}
